/**
 * ABI fragments copied from the P1-generated artifacts. Keep this list small
 * and stable: browser writes use these exact selectors, while receipt/event
 * reads use the same event field names as the relayer.
 */
export const VOLT_TOKEN_ABI = [
  {
    type: "function",
    name: "allowance",
    stateMutability: "view",
    inputs: [{ name: "owner", type: "address" }, { name: "spender", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "approve",
    stateMutability: "nonpayable",
    inputs: [{ name: "spender", type: "address" }, { name: "amount", type: "uint256" }],
    outputs: [{ name: "", type: "bool" }],
  },
  {
    type: "function",
    name: "balanceOf",
    stateMutability: "view",
    inputs: [{ name: "account", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "decimals",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint8" }],
  },
  {
    type: "function",
    name: "faucet",
    stateMutability: "nonpayable",
    inputs: [],
    outputs: [],
  },
  {
    type: "function",
    name: "symbol",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "string" }],
  },
  {
    type: "function",
    name: "transfer",
    stateMutability: "nonpayable",
    inputs: [{ name: "to", type: "address" }, { name: "amount", type: "uint256" }],
    outputs: [{ name: "", type: "bool" }],
  },
  {
    type: "event",
    name: "FaucetClaimed",
    anonymous: false,
    inputs: [
      { indexed: true, name: "account", type: "address" },
      { indexed: false, name: "amountWei", type: "uint256" },
      { indexed: false, name: "nextAvailableAt", type: "uint256" },
    ],
  },
  {
    type: "event",
    name: "Transfer",
    anonymous: false,
    inputs: [
      { indexed: true, name: "from", type: "address" },
      { indexed: true, name: "to", type: "address" },
      { indexed: false, name: "value", type: "uint256" },
    ],
  },
] as const;

export const VOLT_GRID_MARKET_ABI = [
  {
    type: "function",
    name: "deposit",
    stateMutability: "nonpayable",
    inputs: [{ name: "amountWei", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "registerHouse",
    stateMutability: "nonpayable",
    inputs: [
      { name: "hasSolar", type: "bool" },
      { name: "hasBattery", type: "bool" },
      { name: "batteryCapacityWh", type: "uint32" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "getHouses",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "address[]" }],
  },
  {
    type: "function",
    name: "houses",
    stateMutability: "view",
    inputs: [{ name: "", type: "address" }],
    outputs: [
      { name: "exists", type: "bool" },
      { name: "hasSolar", type: "bool" },
      { name: "hasBattery", type: "bool" },
      { name: "batteryCapacityWh", type: "uint32" },
      { name: "batteryOptedIn", type: "bool" },
      { name: "registrationIndex", type: "uint32" },
    ],
  },
  {
    type: "function",
    name: "currentDay",
    stateMutability: "view",
    inputs: [],
    outputs: [
      { name: "active", type: "bool" },
      { name: "id", type: "bytes32" },
      { name: "inputDigest", type: "bytes32" },
      { name: "modelVersion", type: "uint32" },
      { name: "nextEpoch", type: "uint8" },
      { name: "floorMicro", type: "uint64" },
      { name: "baseMicro", type: "uint64" },
      { name: "capMicro", type: "uint64" },
      { name: "feeMicro", type: "uint64" },
      { name: "emergencyActive", type: "bool" },
      { name: "emergencyReported", type: "bool" },
      { name: "emergencyTargetWh", type: "uint32" },
      { name: "emergencyTariffMicro", type: "uint64" },
      { name: "emergencyDeliveredWh", type: "uint32" },
      { name: "emergencyPayoutWei", type: "uint256" },
    ],
  },
  {
    type: "function",
    name: "eligibleWh",
    stateMutability: "view",
    inputs: [{ name: "dayId", type: "bytes32" }, { name: "seller", type: "address" }],
    outputs: [{ name: "", type: "uint32" }],
  },
  {
    type: "function",
    name: "internalBalance",
    stateMutability: "view",
    inputs: [{ name: "", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "setBatteryOptIn",
    stateMutability: "nonpayable",
    inputs: [{ name: "optedIn", type: "bool" }],
    outputs: [],
  },
  {
    type: "function",
    name: "settlementToken",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
  },
  {
    type: "function",
    name: "treasury",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
  },
  {
    type: "function",
    name: "withdraw",
    stateMutability: "nonpayable",
    inputs: [{ name: "amountWei", type: "uint256" }],
    outputs: [],
  },
  {
    type: "event",
    name: "BatteryOptInChanged",
    anonymous: false,
    inputs: [
      { indexed: true, name: "house", type: "address" },
      { indexed: false, name: "optedIn", type: "bool" },
    ],
  },
  {
    type: "event",
    name: "Deposited",
    anonymous: false,
    inputs: [
      { indexed: true, name: "payer", type: "address" },
      { indexed: true, name: "house", type: "address" },
      { indexed: false, name: "amountWei", type: "uint256" },
    ],
  },
  {
    type: "event",
    name: "Withdrawn",
    anonymous: false,
    inputs: [
      { indexed: true, name: "house", type: "address" },
      { indexed: false, name: "amountWei", type: "uint256" },
    ],
  },
  {
    type: "event",
    name: "EmergencyDeclared",
    anonymous: false,
    inputs: [
      { indexed: true, name: "dayId", type: "bytes32" },
      { indexed: true, name: "epochIndex", type: "uint8" },
      { indexed: false, name: "targetWh", type: "uint32" },
      { indexed: false, name: "tariffMicro", type: "uint64" },
    ],
  },
  {
    type: "event",
    name: "BatteryDischarged",
    anonymous: false,
    inputs: [
      { indexed: true, name: "dayId", type: "bytes32" },
      { indexed: true, name: "epochIndex", type: "uint8" },
      { indexed: true, name: "house", type: "address" },
      { indexed: false, name: "deliveredWh", type: "uint32" },
      { indexed: false, name: "payoutWei", type: "uint256" },
    ],
  },
  {
    type: "event",
    name: "EmergencyReportRecorded",
    anonymous: false,
    inputs: [
      { indexed: true, name: "dayId", type: "bytes32" },
      { indexed: true, name: "epochIndex", type: "uint8" },
      { indexed: false, name: "deliveredWh", type: "uint32" },
      { indexed: false, name: "payoutWei", type: "uint256" },
      { indexed: false, name: "dischargeCount", type: "uint8" },
    ],
  },
  {
    type: "event",
    name: "EmergencyResolved",
    anonymous: false,
    inputs: [
      { indexed: true, name: "dayId", type: "bytes32" },
      { indexed: true, name: "epochIndex", type: "uint8" },
      { indexed: false, name: "targetWh", type: "uint32" },
      { indexed: false, name: "shavedWh", type: "uint32" },
      { indexed: false, name: "payoutWei", type: "uint256" },
    ],
  },
  {
    type: "event",
    name: "CarbonFactorApplied",
    anonymous: false,
    inputs: [
      { indexed: true, name: "dayId", type: "bytes32" },
      { indexed: false, name: "factorGPerKwh", type: "uint32" },
      { indexed: false, name: "factorVersion", type: "uint32" },
    ],
  },
  {
    type: "event",
    name: "CertificateMinted",
    anonymous: false,
    inputs: [
      { indexed: true, name: "dayId", type: "bytes32" },
      { indexed: true, name: "solarSeller", type: "address" },
      { indexed: true, name: "tokenId", type: "uint256" },
      { indexed: false, name: "eligibleWh", type: "uint32" },
      { indexed: false, name: "factorGPerKwh", type: "uint32" },
      { indexed: false, name: "avoidedMgCo2e", type: "uint256" },
    ],
  },
] as const;

export const CARBON_CERTIFICATE_ABI = [
  {
    type: "function",
    name: "ownerOf",
    stateMutability: "view",
    inputs: [{ name: "tokenId", type: "uint256" }],
    outputs: [{ name: "", type: "address" }],
  },
  {
    type: "function",
    name: "retired",
    stateMutability: "view",
    inputs: [{ name: "tokenId", type: "uint256" }],
    outputs: [{ name: "", type: "bool" }],
  },
  {
    type: "function",
    name: "retire",
    stateMutability: "nonpayable",
    inputs: [{ name: "tokenId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "certificateData",
    stateMutability: "view",
    inputs: [{ name: "tokenId", type: "uint256" }],
    outputs: [{
      name: "",
      type: "tuple",
      components: [
        { name: "dayId", type: "bytes32" },
        { name: "eligibleWh", type: "uint32" },
        { name: "factorGPerKwh", type: "uint32" },
        { name: "factorVersion", type: "uint32" },
        { name: "avoidedMgCo2e", type: "uint256" },
      ],
    }],
  },
  {
    type: "function",
    name: "tokenURI",
    stateMutability: "view",
    inputs: [{ name: "tokenId", type: "uint256" }],
    outputs: [{ name: "", type: "string" }],
  },
  {
    type: "event",
    name: "CertificateRetired",
    anonymous: false,
    inputs: [
      { indexed: true, name: "tokenId", type: "uint256" },
      { indexed: true, name: "owner", type: "address" },
    ],
  },
] as const;
