import "@nomicfoundation/hardhat-toolbox";
import { HardhatUserConfig } from "hardhat/config";
import * as dotenv from "dotenv";

// Secrets remain in the ignored repository-root .env.local file.
dotenv.config({ path: "../../.env.local" });

// Never use a generic PRIVATE_KEY here: a testnet action must be explicitly
// funded and separated from any unrelated wallet configuration.
const TESTNET_DEPLOYER_KEY = process.env.MST_TESTNET_DEPLOYER_PRIVATE_KEY;
const TESTNET_RPC_URL = process.env.MST_RPC_URL || "https://testnetrpc.mstblockchain.com";
const TESTNET_CHAIN_ID = 91_562_037;

const config: HardhatUserConfig = {
  solidity: {
    version: "0.8.20",
    settings: {
      optimizer: { enabled: true, runs: 200 },
      // The bounded settlement loop has several auditable intermediate
      // values. IR compilation keeps those explicit without unsafe manual
      // stack juggling; P9 must still validate the generated bytecode on MST.
      viaIR: true,
    },
  },
  networks: {
    testnet: {
      url: TESTNET_RPC_URL,
      chainId: TESTNET_CHAIN_ID,
      accounts: TESTNET_DEPLOYER_KEY ? [TESTNET_DEPLOYER_KEY] : [],
    },
  },
  etherscan: {
    apiKey: {
      testnet: process.env.MSTSCAN_API_KEY || "",
    },
    customChains: [
      {
        network: "testnet",
        chainId: 91562037,
        urls: {
          apiURL: "https://testnet.mstscan.com/api",
          browserURL: "https://testnet.mstscan.com",
        },
      },
    ],
  },
};

export default config;
