import fs from "fs";
import path from "path";

type ContractRecord = Record<
  string,
  { address: string; abi: unknown; constructorArguments: unknown[] }
>;
type Deployments = Record<string, ContractRecord>;

const DEPLOYMENTS_JSON = path.join(__dirname, "..", "..", "deployments.json");
const SHARED_CONTRACTS_TS = path.join(
  __dirname,
  "..",
  "..",
  "..",
  "shared",
  "src",
  "contracts.ts"
);

function readDeployments(): Deployments {
  if (!fs.existsSync(DEPLOYMENTS_JSON)) return {};
  return JSON.parse(fs.readFileSync(DEPLOYMENTS_JSON, "utf8"));
}

export function writeDeploymentAddresses(network: string, deployed: ContractRecord): void {
  const all = readDeployments();
  all[network] = { ...(all[network] || {}), ...deployed };

  fs.writeFileSync(DEPLOYMENTS_JSON, JSON.stringify(all, null, 2) + "\n");

  fs.mkdirSync(path.dirname(SHARED_CONTRACTS_TS), { recursive: true });
  fs.writeFileSync(
    SHARED_CONTRACTS_TS,
    `// Auto-generated by \`npm run deploy:testnet\` / \`npm run deploy:mainnet\`.
// Do not edit by hand — changes are overwritten on the next deploy.

export const deployments = ${JSON.stringify(all, null, 2)} as const;

export type NetworkName = keyof typeof deployments;
`
  );
}
